### ISSUE TITLE
Query need for se-lint-ignore entry

### ISSUE THREAD

**Issue by drgrigg** [thewchan/c-s-lewis_poetry#1]
You have a t-003 entry in there to ignore mis-matched quotes in the epigraph. But looking at the epigraph, I would have thought that it could be tagged as verse (though it's blank verse) and the usual poetry/verse styling applied, using `<br/>` between lines, rather than separate paragraphs. Wouldn't that stop the lint error being thrown and be more semantically correct as well?

**Comment by thewchan** [comment]
Thanks David, let me try that.

**Comment by thewchan** [comment]
Fixed with https://github.com/thewchan/c-s-lewis_poetry/commit/b4156ca3561c0472aaa75b019d4fc9f53d5322b4

@drgrigg if you are good with this you can close the issue.
